# Generated by Django 4.2.7 on 2026-01-17 14:24

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_initial'),
        ('payments', '0001_initial'),
        ('core', '0003_alter_tenant_options_tenant_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название счета')),
                ('account_type', models.CharField(choices=[('cash', 'Наличные'), ('bank', 'Банковский счет')], max_length=20, verbose_name='Тип счета')),
                ('currency', models.CharField(choices=[('KGS', 'KGS (сомы)'), ('USD', 'USD (доллары)')], default='KGS', max_length=3, verbose_name='Валюта')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Баланс')),
                ('account_number', models.CharField(blank=True, max_length=100, verbose_name='Номер счета')),
                ('bank_name', models.CharField(blank=True, max_length=255, verbose_name='Название банка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='core.tenant', verbose_name='Владелец (контрагент)')),
            ],
            options={
                'verbose_name': 'Счет',
                'verbose_name_plural': 'Счета',
                'db_table': 'accounts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('income', 'Поступление'), ('expense', 'Расход'), ('transfer_in', 'Перевод (входящий)'), ('transfer_out', 'Перевод (исходящий)'), ('adjustment', 'Корректировка')], max_length=20, verbose_name='Тип операции')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма')),
                ('transaction_date', models.DateField(verbose_name='Дата операции')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='accounts.account', verbose_name='Счет')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('related_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_transactions', to='accounts.account', verbose_name='Связанный счет (для переводов)')),
                ('related_expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_transactions', to='account.expense', verbose_name='Связанный расход')),
                ('related_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_transactions', to='payments.payment', verbose_name='Связанное поступление')),
            ],
            options={
                'verbose_name': 'Операция по счету',
                'verbose_name_plural': 'Операции по счетам',
                'db_table': 'account_transactions',
                'ordering': ['-transaction_date', '-created_at'],
                'indexes': [models.Index(fields=['account', 'transaction_date'], name='account_tra_account_9e9de9_idx')],
            },
        ),
    ]
