# Generated by Django 4.2.7 on 2026-01-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notificationlog',
            new_name='notificatio_accrual_aab696_idx',
            old_name='notification_accrual_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationlog',
            new_name='notificatio_tenant__0cc293_idx',
            old_name='notification_tenant_idx',
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='message_template',
            field=models.TextField(default='Уважаемый {tenant_name}!\n\nНапоминаем, что срок оплаты начисления по договору {contract_number} наступает {due_date}.\nСумма к оплате: {amount} {currency}.\n\nС уважением, Команда ZAKUP.ONE', help_text='Используйте переменные: {tenant_name}, {contract_number}, {due_date}, {amount}, {currency}, {property_name}, {property_address}', verbose_name='Шаблон сообщения'),
        ),
    ]
