# Generated by Django 4.2.7 on 2026-01-16 20:12

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Номер договора')),
                ('signed_at', models.DateField(verbose_name='Дата подписания')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Ставка аренды')),
                ('currency', models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD'), ('EUR', 'EUR')], default='RUB', max_length=3, verbose_name='Валюта')),
                ('due_day', models.IntegerField(default=25, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='День оплаты')),
                ('deposit_enabled', models.BooleanField(default=False, verbose_name='Депозит включён')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Сумма депозита')),
                ('advance_enabled', models.BooleanField(default=False, verbose_name='Аванс включён')),
                ('advance_months', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Месяцев аванса')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активен'), ('ended', 'Завершён'), ('cancelled', 'Отменён')], default='draft', max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='properties.property', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
                'db_table': 'contracts',
                'ordering': ['-created_at'],
            },
        ),
    ]
