# Generated by Django 4.2.7 on 2026-01-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='exchange_rate_source',
            field=models.CharField(choices=[('nbkr', 'НБКР (Национальный банк)'), ('average', 'Средний курс'), ('best', 'Лучший курс')], default='nbkr', max_length=20, verbose_name='Источник курса валют'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='currency',
            field=models.CharField(choices=[('KGS', 'KGS (сомы)'), ('USD', 'USD (доллары)'), ('RUB', 'RUB (рубли)'), ('EUR', 'EUR (евро)')], default='KGS', max_length=3, verbose_name='Валюта'),
        ),
    ]
