# Generated by Django 4.2.7 on 2026-01-23 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_tenant_options_tenant_type'),
        ('contracts', '0003_contract_exchange_rate_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='landlord',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='landlord_contracts', to='core.tenant', verbose_name='Арендодатель'),
        ),
    ]
