# Generated by Django 4.2.7 on 2026-03-06 08:23

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_contractfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractDiscountPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала льготы')),
                ('end_date', models.DateField(verbose_name='Дата окончания льготы')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Скидка (%)')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Причина льготы')),
                ('summary', models.CharField(blank=True, help_text='Напр.: «К оплате 45 000 вместо 50 000 из-за ремонта»', max_length=500, verbose_name='Краткое описание')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_periods', to='contracts.contract', verbose_name='Договор')),
            ],
            options={
                'verbose_name': 'Льготный период',
                'verbose_name_plural': 'Льготные периоды',
                'db_table': 'contract_discount_periods',
                'ordering': ['start_date'],
            },
        ),
    ]
