# Generated by Django 4.2.7 on 2026-01-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название объекта')),
                ('property_type', models.CharField(choices=[('office', 'Офис'), ('shop', 'Магазин'), ('medical', 'Медкабинет'), ('apartment', 'Квартира'), ('warehouse', 'Склад'), ('other', 'Прочее')], max_length=20, verbose_name='Тип недвижимости')),
                ('address', models.CharField(max_length=500, verbose_name='Адрес')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Площадь м²')),
                ('status', models.CharField(choices=[('free', 'Свободен'), ('rented', 'Сдан'), ('reserved', 'Бронь'), ('inactive', 'Неактивен')], default='free', max_length=20, verbose_name='Статус')),
                ('block_floor_room', models.CharField(blank=True, max_length=100, verbose_name='Блок/Этаж/№ помещения')),
                ('owner', models.CharField(blank=True, max_length=255, verbose_name='Владелец')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Объект недвижимости',
                'verbose_name_plural': 'Объекты недвижимости',
                'db_table': 'properties',
                'ordering': ['name'],
            },
        ),
    ]
