# Generated by Django 4.2.7 on 2026-03-11 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_company_and_company_id'),
        ('properties', '0002_property_in_collateral'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='core.company', verbose_name='Компания'),
        ),
    ]
