# Generated by Django 4.2.7 on 2026-01-16 20:12

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('category', models.CharField(choices=[('dividends', 'Дивиденды'), ('utilities', 'Коммунальные'), ('founder', 'Учредителю'), ('repair', 'Мелкий ремонт'), ('salary', 'Зарплата'), ('bonus', 'Бонус'), ('service', 'Обслуживание'), ('transport', 'Транспорт'), ('admin', 'Общий админ расход')], max_length=20, verbose_name='Категория')),
                ('utility_tag', models.CharField(blank=True, choices=[('electricity', 'Свет'), ('water', 'Вода'), ('gas', 'Газ'), ('waste', 'Мусор')], max_length=20, verbose_name='Тег коммуналки')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма')),
                ('recipient', models.CharField(blank=True, max_length=255, verbose_name='Получатель/Кому')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Выплата',
                'verbose_name_plural': 'Выплаты',
                'db_table': 'expenses',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
