# Generated by Django 4.2.7 on 2026-01-16 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('properties', '0001_initial'),
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='contracts.contract', verbose_name='Договор'),
        ),
        migrations.AddField(
            model_name='expense',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='properties.property', verbose_name='Объект'),
        ),
    ]
