# Generated by Django 4.2.7 on 2026-01-16 20:12

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Сумма депозита')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Остаток')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deposit', to='contracts.contract', verbose_name='Договор')),
            ],
            options={
                'verbose_name': 'Депозит',
                'verbose_name_plural': 'Депозиты',
                'db_table': 'deposits',
            },
        ),
        migrations.CreateModel(
            name='DepositMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Внесение'), ('out', 'Списание'), ('refund', 'Возврат')], max_length=20, verbose_name='Тип движения')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма')),
                ('reason', models.CharField(blank=True, choices=[('debt', 'Погашение долга'), ('damage', 'Ущерб'), ('other', 'Прочее')], max_length=20, verbose_name='Причина')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='deposits.deposit', verbose_name='Депозит')),
            ],
            options={
                'verbose_name': 'Движение по депозиту',
                'verbose_name_plural': 'Движения по депозитам',
                'db_table': 'deposit_movements',
                'ordering': ['-created_at'],
            },
        ),
    ]
