# Generated by Django 4.2.7 on 2026-03-11 12:10

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0014_add_company_and_company_id'),
        ('properties', '0003_add_company_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investment_projects', to='properties.property', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Инвестиционный проект',
                'verbose_name_plural': 'Инвестиционные проекты',
                'db_table': 'investment_projects',
            },
        ),
        migrations.CreateModel(
            name='InvestorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('period_from', models.DateField(blank=True, null=True, verbose_name='Период с')),
                ('period_to', models.DateField(blank=True, null=True, verbose_name='Период по')),
                ('file', models.FileField(blank=True, null=True, upload_to='investor_reports/%Y/%m/', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_reports', to='core.tenant', verbose_name='Инвестор')),
            ],
            options={
                'verbose_name': 'Отчёт инвестору',
                'verbose_name_plural': 'Отчёты инвесторам',
                'db_table': 'investor_reports',
            },
        ),
        migrations.CreateModel(
            name='InvestorPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Сумма вложения')),
                ('date_from', models.DateField(verbose_name='Дата входа')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Дата выхода')),
                ('share_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Доля (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_positions', to='core.tenant', verbose_name='Инвестор')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='investor_portal.investmentproject', verbose_name='Проект')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investor_positions', to='properties.property', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Позиция инвестора',
                'verbose_name_plural': 'Позиции инвесторов',
                'db_table': 'investor_positions',
            },
        ),
        migrations.CreateModel(
            name='InvestorPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('payout_date', models.DateField(verbose_name='Дата выплаты')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_payouts', to='core.tenant', verbose_name='Инвестор')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts', to='investor_portal.investmentproject', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Выплата инвестору',
                'verbose_name_plural': 'Выплаты инвесторам',
                'db_table': 'investor_payouts',
            },
        ),
    ]
