# Generated by Django 4.2.7 on 2026-01-16 20:12

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accrual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='Начало периода')),
                ('period_end', models.DateField(verbose_name='Конец периода')),
                ('due_date', models.DateField(verbose_name='Срок оплаты')),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Базовая сумма (аренда)')),
                ('adjustments', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Корректировки')),
                ('utilities_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Коммунальные услуги')),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Итоговая сумма')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Оплачено')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Остаток')),
                ('status', models.CharField(choices=[('planned', 'Ожидает'), ('due', 'К оплате'), ('overdue', 'Просрочено'), ('partial', 'Частично оплачено'), ('paid', 'Оплачено')], default='planned', max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Начисление',
                'verbose_name_plural': 'Начисления',
                'db_table': 'accruals',
                'ordering': ['contract', 'period_start'],
            },
        ),
    ]
