# Generated by Django 4.2.7 on 2026-01-16 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accruals', '0001_initial'),
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accrual',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accruals', to='contracts.contract', verbose_name='Договор'),
        ),
        migrations.AddIndex(
            model_name='accrual',
            index=models.Index(fields=['contract', 'period_start'], name='accruals_contrac_fa12b2_idx'),
        ),
        migrations.AddIndex(
            model_name='accrual',
            index=models.Index(fields=['status', 'due_date'], name='accruals_status_3e336a_idx'),
        ),
    ]
