# Generated by Django 4.2.7 on 2026-01-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accruals', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accrual',
            name='utility_type',
            field=models.CharField(choices=[('rent', 'Аренда'), ('electricity', 'Электричество'), ('water', 'Вода'), ('gas', 'Газ'), ('garbage', 'Мусор'), ('service', 'Сервисное обслуживание'), ('salary', 'Зарплата'), ('transport', 'Транспортные расходы'), ('other', 'Прочие расходы')], default='rent', max_length=20, verbose_name='Тип начисления'),
        ),
    ]
