# Generated by Django 4.2.7 on 2026-01-24 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accruals', '0003_accrual_utility_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accrual',
            options={'ordering': ['due_date', 'id'], 'verbose_name': 'Начисление', 'verbose_name_plural': 'Начисления'},
        ),
    ]
