# Generated by Django 4.2.7 on 2026-01-16 20:12

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accruals', '0001_initial'),
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма')),
                ('payment_date', models.DateField(verbose_name='Дата платежа')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Распределено')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='contracts.contract', verbose_name='Договор')),
            ],
            options={
                'verbose_name': 'Поступление',
                'verbose_name_plural': 'Поступления',
                'db_table': 'payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сумма распределения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accrual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='accruals.accrual', verbose_name='Начисление')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='payments.payment', verbose_name='Платеж')),
            ],
            options={
                'verbose_name': 'Распределение платежа',
                'verbose_name_plural': 'Распределения платежей',
                'db_table': 'payment_allocations',
                'indexes': [models.Index(fields=['payment'], name='payment_all_payment_722e23_idx'), models.Index(fields=['accrual'], name='payment_all_accrual_8a9594_idx')],
                'unique_together': {('payment', 'accrual')},
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['contract', 'payment_date'], name='payments_contrac_deb047_idx'),
        ),
    ]
