# Generated by Django 4.2.7 on 2026-01-21 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_add_account_to_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_returned',
            field=models.BooleanField(default=False, verbose_name='Возвращен'),
        ),
    ]
