# Generated by Django 4.2.7 on 2026-01-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3, verbose_name='Валюта')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Курс к сому')),
                ('source', models.CharField(choices=[('nbkr', 'НБКР (Национальный банк)'), ('average', 'Средний курс'), ('best', 'Лучший курс')], default='nbkr', max_length=20, verbose_name='Источник')),
                ('date', models.DateField(verbose_name='Дата')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Курс валют',
                'verbose_name_plural': 'Курсы валют',
                'db_table': 'exchange_rates',
                'ordering': ['-date', 'currency'],
                'unique_together': {('currency', 'source', 'date')},
            },
        ),
    ]
