# Generated by Django 4.2.7 on 2026-01-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_exchangerate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['name'], 'verbose_name': 'Контрагент', 'verbose_name_plural': 'Контрагенты'},
        ),
        migrations.AddField(
            model_name='tenant',
            name='type',
            field=models.CharField(choices=[('tenant', 'Арендатор'), ('landlord', 'Арендодатель'), ('staff', 'Сотрудник'), ('master', 'Мастер'), ('company_owner', 'Владелец компании'), ('property_owner', 'Хозяин недвижимости'), ('investor', 'Инвестор')], default='tenant', max_length=20, verbose_name='Тип'),
        ),
    ]
