# Generated by Django 4.2.7 on 2026-01-23 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
        ('contracts', '0004_contract_landlord'),
        ('core', '0003_alter_tenant_options_tenant_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='user',
            name='counterparty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.tenant', verbose_name='Контрагент'),
        ),
        migrations.AddField(
            model_name='user',
            name='preferences',
            field=models.JSONField(blank=True, default=dict, verbose_name='Настройки'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Сотрудник'), ('tenant', 'Арендатор'), ('landlord', 'Арендодатель'), ('investor', 'Инвестор')], default='staff', max_length=20, verbose_name='Роль'),
        ),
        migrations.CreateModel(
            name='StaffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='contracts.contract', verbose_name='Договор')),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='core.tenant', verbose_name='Контрагент')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='properties.property', verbose_name='Объект')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Назначение сотрудника',
                'verbose_name_plural': 'Назначения сотрудников',
                'db_table': 'staff_assignments',
                'unique_together': {('staff', 'contract'), ('staff', 'property'), ('staff', 'counterparty')},
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('role', models.CharField(max_length=20, verbose_name='Роль создателя')),
                ('type', models.CharField(choices=[('CHANGE_CONTACTS', 'Изменение контактов'), ('CHANGE_REQUISITES', 'Изменение реквизитов'), ('CONTRACT_QUESTION', 'Вопрос по договору'), ('PAYMENT_QUESTION', 'Вопрос по платежам'), ('REQUEST_DOCUMENT', 'Запрос документа/справки'), ('PROPERTY_ISSUE', 'Проблема с объектом'), ('OTHER', 'Прочее')], max_length=30, verbose_name='Тип заявки')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='Вложения')),
                ('status', models.CharField(choices=[('NEW', 'Новая'), ('IN_REVIEW', 'На рассмотрении'), ('NEED_INFO', 'Требуется информация'), ('APPROVED', 'Одобрена'), ('REJECTED', 'Отклонена'), ('DONE', 'Выполнена')], default='NEW', max_length=20, verbose_name='Статус')),
                ('internal_comment', models.TextField(blank=True, verbose_name='Внутренний комментарий')),
                ('public_reply', models.TextField(blank=True, verbose_name='Публичный ответ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL, verbose_name='Назначено')),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='core.tenant', verbose_name='Контрагент')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_requests', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('related_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='contracts.contract', verbose_name='Связанный договор')),
                ('related_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='properties.property', verbose_name='Связанный объект')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'db_table': 'requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='requests_status_e58b13_idx'), models.Index(fields=['created_by', 'status'], name='requests_created_5c12b6_idx'), models.Index(fields=['assigned_to', 'status'], name='requests_assigne_815d2c_idx')],
            },
        ),
        migrations.CreateModel(
            name='InvestorLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share', models.DecimalField(decimal_places=2, default=100.0, max_digits=5, verbose_name='Доля (%)')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('inactive', 'Неактивна')], default='active', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investor_links', to='contracts.contract', verbose_name='Договор')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_links', to='core.tenant', verbose_name='Инвестор')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investor_links', to='properties.property', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Связь инвестора',
                'verbose_name_plural': 'Связи инвесторов',
                'db_table': 'investor_links',
                'unique_together': {('investor', 'contract'), ('investor', 'property')},
            },
        ),
    ]
