# Generated by Django 4.2.7 on 2026-01-24 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_loginattempt'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='loginattempt',
            new_name='login_attem_attempt_797412_idx',
            old_name='login_atte_attempt_2b3c4d_idx',
        ),
        migrations.RenameIndex(
            model_name='loginattempt',
            new_name='login_attem_status_ea51ce_idx',
            old_name='login_atte_status_5a8f2e_idx',
        ),
        migrations.RenameIndex(
            model_name='loginattempt',
            new_name='login_attem_verifie_e15f1c_idx',
            old_name='login_atte_verifie_8d9c1f_idx',
        ),
        migrations.AddField(
            model_name='loginattempt',
            name='otp_code',
            field=models.CharField(blank=True, db_index=True, max_length=6, null=True, verbose_name='OTP код'),
        ),
    ]
