# Generated by Django 4.2.7 on 2026-01-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_login_atte_attempt_2b3c4d_idx_login_attem_attempt_797412_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='type',
            field=models.CharField(choices=[('admin', 'Администратор'), ('tenant', 'Арендатор'), ('landlord', 'Арендодатель'), ('staff', 'Сотрудник'), ('master', 'Мастер'), ('company_owner', 'Владелец компании'), ('property_owner', 'Хозяин недвижимости'), ('investor', 'Инвестор')], default='tenant', max_length=20, verbose_name='Тип'),
        ),
    ]
