# Generated by Django 4.2.7 on 2026-03-11 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_tenant_additional_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug (для subdomain)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='Настройки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'db_table': 'companies',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='tenant',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='core.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Null = доступ ко всем данным (текущий режим)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.company', verbose_name='Компания'),
        ),
    ]
